baseurl = "https://krossovochkin.github.io/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
publishDir = ".."
staticDir = "static"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "yellow"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "krossovochkin"
  site = "krossovochkin"

[languages]
  [languages.en]
    languageName = "English"
    title = "Krossovochkin"
    subtitle = "Android Developer"
    owner = ""
    keywords = ""
    copyright = "Â© 2020 Vasya Drobushkov"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Krossovochkin"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About me"
        url = "/about"